### PR TITLE
Fix array merging for includes and excludes (resolves #29).

### LINKED ISSUE #29: Array values do not override properly in sources
When adding, for example, a sources entry which looks as follows:

````
    "sources": {
        "css": ["./thing.css"], 
````

the resulting value received by the linter still retains mouse droppings of the last two entries in the grade defaults, e.g. 

````
  includes: [ './thing.css', './src/**/*.css', 'tests/**/*.css' ],
````
This is unlikely to be what the user intended. There should be a mergePolicy applied here to displace the default values.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See #29 for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
@greatislander, I cut `1.0.5-dev.20210416T143028Z.dfea15d.GH-29`, which follows a strategy somewhere between what Antranig and I discussed here and what you asked for in #21:

> The default excludes should be present in the merged configuration.

File: src/js/mapMerge.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+"use strict";
+var fluid = require("infusion");
+fluid.registerNamespace("fluid.lintAll");
+
+fluid.lintAll.mapMerge = function (baseArray, toMergeArray) {
```
Comment (amb26) [inline src/js/mapMerge.js:5]: Some JSDocs and strategy comments would be helpful here - what does this function achieve?

Comment (the-t-in-rtf) [reply src/js/mapMerge.js:5]: I have added JSDocs to describe what the trio of functions does.  The previous docs were inaccurate and described the old behaviour.  I have updated those as well.

File: src/js/mapMerge.js [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+ *
+ * @param {String} glob - A single "glob" pattern.
+ * @return {Object} - A single-entry object whose key is the glob pattern, and whose value indicates whether the
+ * value is positive or negated.
+ *
+ */
+fluid.lintAll.globToMapEntry = function (glob) {
+    var isPositive = glob.indexOf("!") !== 0;
+    var entryValue = isPositive ? glob : glob.substring(1);
+    var toReturn = {};
```
Comment (amb26) [inline src/js/mapMerge.js:66]: In case you were interested in moving on up to ES6 source, this is a classic case for ES6-style dynamic/computed keys: https://stackoverflow.com/a/19837961

File: src/js/mapMerge.js [hunk 3]
```diff
@@ -0,0 +1,69 @@
...
+ *
+ * Convert a glob pattern to a single-entry object that can be merged with other converted glob patterns.
+ *
+ * @param {String} glob - A single "glob" pattern.
+ * @return {Object} - A single-entry object whose key is the glob pattern, and whose value indicates whether the
+ * value is positive or negated.
+ *
+ */
+fluid.lintAll.globToMapEntry = function (glob) {
+    var isPositive = glob.indexOf("!") !== 0;
```
Comment (amb26) [inline src/js/mapMerge.js:64]: Slightly clearer and more efficient would be glob.charAt(0) !== "!"

Comment (the-t-in-rtf) [reply src/js/mapMerge.js]: Done.

File: src/js/mapMerge.js (hunk 2 above)
Comment (the-t-in-rtf) [reply src/js/mapMerge.js:66]: I may hold off for now, but I'll have to try it on the projects where we already use it.

**Comment by amb26** [comment]
I get the following test failures (13) on my system (Windows 7, node 14.15.4, npm 6.14.11)
````
13:09:52.736:  jq: FAIL: Module "Tests for the fluid-lint-all launcher." Test name "We should be able to exclude files included in a .gitignore file." - Message
: Check 'lintspaces.jsonindentation' should not have reported invalid content.
13:09:52.738:  jq: Source:     at pok (E:\source\gits\fluid-lint-all\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:109:15)
    at Object.fail (E:\source\gits\fluid-lint-all\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:126:13)
    at E:\source\gits\fluid-lint-all\tests\js\launcher-tests.js:36:24
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
13:09:52.777:  jq: FAIL: Module "Tests for the fluid-lint-all launcher." Test name "We should be able to exclude files included in a .gitignore file." - Message
: Check 'lintspaces' should not have reported invalid content.
13:09:52.778:  jq: Source:     at pok (E:\source\gits\fluid-lint-all\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:109:15)
    at Object.fail (E:\source\gits\fluid-lint-all\node_modules\infusion\tests\test-core\jqUnit\js\jqUnit.js:126:13)
    at E:\source\gits\fluid-lint-all\tests\js\launcher-tests.js:36:24
    at ChildProcess.exithandler (child_process.js:315:5)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
````
etc.
And then also failure 
`````
ERROR: Coverage for branches (88.6%) does not meet global threshold (90%)
`````

These failures are also in main and presumably a result of merging https://github.com/fluid-project/fluid-lint-all/pull/19

I expect the cause of the failure is the parsing strategy at https://github.com/fluid-project/fluid-lint-all/pull/19/files#diff-17dc7e461493eba4d0b0b632a74d2ed2a64a0b4175208fedc110a3f2d8c2773bR50 which splits the file on "\n". Note that the recommended strategy for reading files by line on node is described in https://nodejs.org/api/readline.html

**Comment by the-t-in-rtf** [comment]
> Note that the recommended strategy for reading files by line on node is described in https://nodejs.org/api/readline.html

There are several strategies in that file, all of which require converting to using asynchronous functions, which I would rather avoid if possible.

I updated the split to use a hopefully more robust regex, not sure if that helps.  If that doesn't help, I would appreciate it if you could confirm with a debugger what the array of parsed excludes looks like when you run the tests.

**Comment by the-t-in-rtf** [comment]
I see the issues in a Windows 10 VM, but I also see that six entries are found.  I think the problem might actually be with the pathing immediately below that spot.
